#############################################################################
# Makefile for building: untitled
# Generated by qmake (3.1) (Qt 6.6.3)
# Project:  untitled.pro
# Template: app
# Command: /home/lekhacvuong/Qt/6.6.3/gcc_64/bin/qmake -o Makefile untitled.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -InanoModbus -Imb_master -Iutils -Iutils/timing -I../6.6.3/gcc_64/include -I../6.6.3/gcc_64/include/QtWidgets -I../6.6.3/gcc_64/include/QtGui -I../6.6.3/gcc_64/include/QtBluetooth -I../6.6.3/gcc_64/include/QtNetwork -I../6.6.3/gcc_64/include/QtDBus -I../6.6.3/gcc_64/include/QtCore -I. -I. -I../6.6.3/gcc_64/mkspecs/linux-g++
QMAKE         = /home/lekhacvuong/Qt/6.6.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/lekhacvuong/Qt/6.6.3/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/lekhacvuong/Qt/6.6.3/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = untitled1.0.0
DISTDIR = /home/lekhacvuong/Qt/untitled/.tmp/untitled1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/lekhacvuong/Qt/6.6.3/gcc_64/lib
LIBS          = $(SUBLIBS) /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6Widgets.so /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6Gui.so /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6Bluetooth.so -pthread /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6Network.so /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6DBus.so /home/lekhacvuong/Qt/6.6.3/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mb_master/sm_mb_master_impl.c \
		nanoModbus/nanomodbus.c \
		utils/sm_logger.c \
		utils/timing/DateTime.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sm_mb_master_impl.o \
		nanomodbus.o \
		sm_logger.o \
		DateTime.o \
		moc_mainwindow.o
DIST          = ../6.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		../6.6.3/gcc_64/mkspecs/common/unix.conf \
		../6.6.3/gcc_64/mkspecs/common/linux.conf \
		../6.6.3/gcc_64/mkspecs/common/sanitize.conf \
		../6.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		../6.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../6.6.3/gcc_64/mkspecs/common/g++-base.conf \
		../6.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../6.6.3/gcc_64/mkspecs/qconfig.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_archive.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_yaml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_application_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_common_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_main_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_package_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_window_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../6.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../6.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../6.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../6.6.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../6.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../6.6.3/gcc_64/mkspecs/features/toolchain.prf \
		../6.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../6.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../6.6.3/gcc_64/mkspecs/features/default_post.prf \
		../6.6.3/gcc_64/mkspecs/features/qml_debug.prf \
		../6.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../6.6.3/gcc_64/mkspecs/features/permissions.prf \
		../6.6.3/gcc_64/mkspecs/features/qt.prf \
		../6.6.3/gcc_64/mkspecs/features/resources_functions.prf \
		../6.6.3/gcc_64/mkspecs/features/resources.prf \
		../6.6.3/gcc_64/mkspecs/features/moc.prf \
		../6.6.3/gcc_64/mkspecs/features/dbuscommon.pri \
		../6.6.3/gcc_64/mkspecs/features/dbusinterfaces.prf \
		../6.6.3/gcc_64/mkspecs/features/dbusadaptors.prf \
		../6.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../6.6.3/gcc_64/mkspecs/features/uic.prf \
		../6.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../6.6.3/gcc_64/mkspecs/features/qmake_use.prf \
		../6.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../6.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../6.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../6.6.3/gcc_64/mkspecs/features/yacc.prf \
		../6.6.3/gcc_64/mkspecs/features/lex.prf \
		untitled.pro mainwindow.h \
		mb_master/sm_mb_master_if.h \
		mb_master/sm_mb_master_impl.h \
		mb_master/sm_modbus_define.h \
		nanoModbus/nanomodbus.h \
		utils/sm_logger.h \
		utils/timing/DateTime.h \
		utils/timing/TimeUtils.h \
		utils/timing/Timer.h \
		utils/timing/elapsed_timer.h main.cpp \
		mainwindow.cpp \
		mb_master/sm_mb_master_impl.c \
		nanoModbus/nanomodbus.c \
		utils/sm_logger.c \
		utils/timing/DateTime.cpp
QMAKE_TARGET  = untitled
DESTDIR       = 
TARGET        = untitled


first: all
####### Build rules

untitled: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled.pro ../6.6.3/gcc_64/mkspecs/linux-g++/qmake.conf ../6.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		../6.6.3/gcc_64/mkspecs/common/unix.conf \
		../6.6.3/gcc_64/mkspecs/common/linux.conf \
		../6.6.3/gcc_64/mkspecs/common/sanitize.conf \
		../6.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		../6.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../6.6.3/gcc_64/mkspecs/common/g++-base.conf \
		../6.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../6.6.3/gcc_64/mkspecs/qconfig.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_archive.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_ext_yaml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_application_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_common_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_main_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_package_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_window_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../6.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../6.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../6.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../6.6.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../6.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../6.6.3/gcc_64/mkspecs/features/toolchain.prf \
		../6.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../6.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../6.6.3/gcc_64/mkspecs/features/default_post.prf \
		../6.6.3/gcc_64/mkspecs/features/qml_debug.prf \
		../6.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../6.6.3/gcc_64/mkspecs/features/permissions.prf \
		../6.6.3/gcc_64/mkspecs/features/qt.prf \
		../6.6.3/gcc_64/mkspecs/features/resources_functions.prf \
		../6.6.3/gcc_64/mkspecs/features/resources.prf \
		../6.6.3/gcc_64/mkspecs/features/moc.prf \
		../6.6.3/gcc_64/mkspecs/features/dbuscommon.pri \
		../6.6.3/gcc_64/mkspecs/features/dbusinterfaces.prf \
		../6.6.3/gcc_64/mkspecs/features/dbusadaptors.prf \
		../6.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../6.6.3/gcc_64/mkspecs/features/uic.prf \
		../6.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../6.6.3/gcc_64/mkspecs/features/qmake_use.prf \
		../6.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../6.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../6.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../6.6.3/gcc_64/mkspecs/features/yacc.prf \
		../6.6.3/gcc_64/mkspecs/features/lex.prf \
		untitled.pro \
		../6.6.3/gcc_64/lib/libQt6Widgets.prl \
		../6.6.3/gcc_64/lib/libQt6Gui.prl \
		../6.6.3/gcc_64/lib/libQt6Bluetooth.prl \
		../6.6.3/gcc_64/lib/libQt6Network.prl \
		../6.6.3/gcc_64/lib/libQt6DBus.prl \
		../6.6.3/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile untitled.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../6.6.3/gcc_64/mkspecs/features/spec_pre.prf:
../6.6.3/gcc_64/mkspecs/common/unix.conf:
../6.6.3/gcc_64/mkspecs/common/linux.conf:
../6.6.3/gcc_64/mkspecs/common/sanitize.conf:
../6.6.3/gcc_64/mkspecs/common/gcc-base.conf:
../6.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../6.6.3/gcc_64/mkspecs/common/g++-base.conf:
../6.6.3/gcc_64/mkspecs/common/g++-unix.conf:
../6.6.3/gcc_64/mkspecs/qconfig.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_ext_archive.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_ext_yaml.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_application_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_common_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_crypto_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_dbus_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_client_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_intent_server_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_launcher_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_main_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_manager_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_monitor_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_notification_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_package_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_shared_main_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_appman_window_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../6.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../6.6.3/gcc_64/mkspecs/features/qt_functions.prf:
../6.6.3/gcc_64/mkspecs/features/qt_config.prf:
../6.6.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../6.6.3/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../6.6.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../6.6.3/gcc_64/mkspecs/features/toolchain.prf:
../6.6.3/gcc_64/mkspecs/features/default_pre.prf:
../6.6.3/gcc_64/mkspecs/features/resolve_config.prf:
../6.6.3/gcc_64/mkspecs/features/default_post.prf:
../6.6.3/gcc_64/mkspecs/features/qml_debug.prf:
../6.6.3/gcc_64/mkspecs/features/warn_on.prf:
../6.6.3/gcc_64/mkspecs/features/permissions.prf:
../6.6.3/gcc_64/mkspecs/features/qt.prf:
../6.6.3/gcc_64/mkspecs/features/resources_functions.prf:
../6.6.3/gcc_64/mkspecs/features/resources.prf:
../6.6.3/gcc_64/mkspecs/features/moc.prf:
../6.6.3/gcc_64/mkspecs/features/dbuscommon.pri:
../6.6.3/gcc_64/mkspecs/features/dbusinterfaces.prf:
../6.6.3/gcc_64/mkspecs/features/dbusadaptors.prf:
../6.6.3/gcc_64/mkspecs/features/unix/opengl.prf:
../6.6.3/gcc_64/mkspecs/features/uic.prf:
../6.6.3/gcc_64/mkspecs/features/unix/thread.prf:
../6.6.3/gcc_64/mkspecs/features/qmake_use.prf:
../6.6.3/gcc_64/mkspecs/features/file_copies.prf:
../6.6.3/gcc_64/mkspecs/features/testcase_targets.prf:
../6.6.3/gcc_64/mkspecs/features/exceptions.prf:
../6.6.3/gcc_64/mkspecs/features/yacc.prf:
../6.6.3/gcc_64/mkspecs/features/lex.prf:
untitled.pro:
../6.6.3/gcc_64/lib/libQt6Widgets.prl:
../6.6.3/gcc_64/lib/libQt6Gui.prl:
../6.6.3/gcc_64/lib/libQt6Bluetooth.prl:
../6.6.3/gcc_64/lib/libQt6Network.prl:
../6.6.3/gcc_64/lib/libQt6DBus.prl:
../6.6.3/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile untitled.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile untitled

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../6.6.3/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h mb_master/sm_mb_master_if.h mb_master/sm_mb_master_impl.h mb_master/sm_modbus_define.h nanoModbus/nanomodbus.h utils/sm_logger.h utils/timing/DateTime.h utils/timing/TimeUtils.h utils/timing/Timer.h utils/timing/elapsed_timer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mb_master/sm_mb_master_impl.c nanoModbus/nanomodbus.c utils/sm_logger.c utils/timing/DateTime.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../6.6.3/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h ../6.6.3/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/QMainWindow \
		../6.6.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../6.6.3/gcc_64/include/QtGui/qtguiglobal.h \
		../6.6.3/gcc_64/include/QtCore/qglobal.h \
		../6.6.3/gcc_64/include/QtCore/qtversionchecks.h \
		../6.6.3/gcc_64/include/QtCore/qtconfiginclude.h \
		../6.6.3/gcc_64/include/QtCore/qconfig.h \
		../6.6.3/gcc_64/include/QtCore/qtcore-config.h \
		../6.6.3/gcc_64/include/QtCore/qtconfigmacros.h \
		../6.6.3/gcc_64/include/QtCore/qtcoreexports.h \
		../6.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../6.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../6.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../6.6.3/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../6.6.3/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../6.6.3/gcc_64/include/QtCore/qassert.h \
		../6.6.3/gcc_64/include/QtCore/qtnoop.h \
		../6.6.3/gcc_64/include/QtCore/qtypes.h \
		../6.6.3/gcc_64/include/QtCore/qtversion.h \
		../6.6.3/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../6.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../6.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../6.6.3/gcc_64/include/QtCore/qlogging.h \
		../6.6.3/gcc_64/include/QtCore/qflags.h \
		../6.6.3/gcc_64/include/QtCore/qcompare_impl.h \
		../6.6.3/gcc_64/include/QtCore/qatomic.h \
		../6.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../6.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../6.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../6.6.3/gcc_64/include/QtCore/qconstructormacros.h \
		../6.6.3/gcc_64/include/QtCore/qdarwinhelpers.h \
		../6.6.3/gcc_64/include/QtCore/qexceptionhandling.h \
		../6.6.3/gcc_64/include/QtCore/qforeach.h \
		../6.6.3/gcc_64/include/QtCore/qttypetraits.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionpointer.h \
		../6.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../6.6.3/gcc_64/include/QtCore/qmalloc.h \
		../6.6.3/gcc_64/include/QtCore/qminmax.h \
		../6.6.3/gcc_64/include/QtCore/qnumeric.h \
		../6.6.3/gcc_64/include/QtCore/qoverload.h \
		../6.6.3/gcc_64/include/QtCore/qswap.h \
		../6.6.3/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../6.6.3/gcc_64/include/QtCore/qtresource.h \
		../6.6.3/gcc_64/include/QtCore/qttranslation.h \
		../6.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../6.6.3/gcc_64/include/QtGui/qtgui-config.h \
		../6.6.3/gcc_64/include/QtGui/qtguiexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../6.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../6.6.3/gcc_64/include/QtCore/qnamespace.h \
		../6.6.3/gcc_64/include/QtCore/qtmetamacros.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qobject.h \
		../6.6.3/gcc_64/include/QtCore/qstring.h \
		../6.6.3/gcc_64/include/QtCore/qchar.h \
		../6.6.3/gcc_64/include/QtCore/qstringview.h \
		../6.6.3/gcc_64/include/QtCore/qbytearray.h \
		../6.6.3/gcc_64/include/QtCore/qrefcount.h \
		../6.6.3/gcc_64/include/QtCore/qarraydata.h \
		../6.6.3/gcc_64/include/QtCore/qpair.h \
		../6.6.3/gcc_64/include/QtCore/qarraydatapointer.h \
		../6.6.3/gcc_64/include/QtCore/qarraydataops.h \
		../6.6.3/gcc_64/include/QtCore/qcontainertools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qxptype_traits.h \
		../6.6.3/gcc_64/include/QtCore/q20functional.h \
		../6.6.3/gcc_64/include/QtCore/q20memory.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayview.h \
		../6.6.3/gcc_64/include/QtCore/qstringfwd.h \
		../6.6.3/gcc_64/include/QtCore/q20type_traits.h \
		../6.6.3/gcc_64/include/QtCore/qstringliteral.h \
		../6.6.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qlatin1stringview.h \
		../6.6.3/gcc_64/include/QtCore/qanystringview.h \
		../6.6.3/gcc_64/include/QtCore/qutf8stringview.h \
		../6.6.3/gcc_64/include/QtCore/qstringtokenizer.h \
		../6.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../6.6.3/gcc_64/include/QtCore/qlist.h \
		../6.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../6.6.3/gcc_64/include/QtCore/qiterator.h \
		../6.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../6.6.3/gcc_64/include/QtCore/qstringlist.h \
		../6.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../6.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../6.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qmetatype.h \
		../6.6.3/gcc_64/include/QtCore/qcompare.h \
		../6.6.3/gcc_64/include/QtCore/qdatastream.h \
		../6.6.3/gcc_64/include/QtCore/qiodevicebase.h \
		../6.6.3/gcc_64/include/QtCore/qfloat16.h \
		../6.6.3/gcc_64/include/QtCore/qmath.h \
		../6.6.3/gcc_64/include/QtCore/qiterable.h \
		../6.6.3/gcc_64/include/QtCore/qmetacontainer.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerinfo.h \
		../6.6.3/gcc_64/include/QtCore/qtaggedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qscopeguard.h \
		../6.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../6.6.3/gcc_64/include/QtCore/qbindingstorage.h \
		../6.6.3/gcc_64/include/QtCore/qmargins.h \
		../6.6.3/gcc_64/include/QtCore/q23utility.h \
		../6.6.3/gcc_64/include/QtGui/qaction.h \
		../6.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../6.6.3/gcc_64/include/QtGui/qicon.h \
		../6.6.3/gcc_64/include/QtCore/qsize.h \
		../6.6.3/gcc_64/include/QtGui/qpixmap.h \
		../6.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../6.6.3/gcc_64/include/QtCore/qrect.h \
		../6.6.3/gcc_64/include/QtCore/qpoint.h \
		../6.6.3/gcc_64/include/QtGui/qcolor.h \
		../6.6.3/gcc_64/include/QtGui/qrgb.h \
		../6.6.3/gcc_64/include/QtGui/qrgba64.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata.h \
		../6.6.3/gcc_64/include/QtGui/qimage.h \
		../6.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../6.6.3/gcc_64/include/QtGui/qtransform.h \
		../6.6.3/gcc_64/include/QtGui/qpolygon.h \
		../6.6.3/gcc_64/include/QtGui/qregion.h \
		../6.6.3/gcc_64/include/QtCore/qline.h \
		../6.6.3/gcc_64/include/QtCore/qvariant.h \
		../6.6.3/gcc_64/include/QtCore/qdebug.h \
		../6.6.3/gcc_64/include/QtCore/qtextstream.h \
		../6.6.3/gcc_64/include/QtCore/qstringconverter_base.h \
		../6.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../6.6.3/gcc_64/include/QtCore/qmap.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata_impl.h \
		../6.6.3/gcc_64/include/QtCore/qset.h \
		../6.6.3/gcc_64/include/QtCore/qhash.h \
		../6.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../6.6.3/gcc_64/include/QtGui/qpalette.h \
		../6.6.3/gcc_64/include/QtGui/qbrush.h \
		../6.6.3/gcc_64/include/QtGui/qfont.h \
		../6.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../6.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../6.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../6.6.3/gcc_64/include/QtGui/qcursor.h \
		../6.6.3/gcc_64/include/QtGui/qbitmap.h \
		../6.6.3/gcc_64/include/QtGui/qevent.h \
		../6.6.3/gcc_64/include/QtCore/qiodevice.h \
		../6.6.3/gcc_64/include/QtCore/qpointer.h \
		../6.6.3/gcc_64/include/QtCore/qurl.h \
		../6.6.3/gcc_64/include/QtGui/qeventpoint.h \
		../6.6.3/gcc_64/include/QtGui/qvector2d.h \
		../6.6.3/gcc_64/include/QtGui/qvectornd.h \
		../6.6.3/gcc_64/include/QtGui/qpointingdevice.h \
		../6.6.3/gcc_64/include/QtGui/qinputdevice.h \
		../6.6.3/gcc_64/include/QtGui/qscreen.h \
		../6.6.3/gcc_64/include/QtCore/QList \
		../6.6.3/gcc_64/include/QtCore/QObject \
		../6.6.3/gcc_64/include/QtCore/QRect \
		../6.6.3/gcc_64/include/QtCore/QSize \
		../6.6.3/gcc_64/include/QtCore/QSizeF \
		../6.6.3/gcc_64/include/QtGui/QTransform \
		../6.6.3/gcc_64/include/QtCore/qnativeinterface.h \
		../6.6.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothexports.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceInfo \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothUuid \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		../6.6.3/gcc_64/include/QtCore/QtGlobal \
		../6.6.3/gcc_64/include/QtCore/QMetaType \
		../6.6.3/gcc_64/include/QtCore/QUuid \
		../6.6.3/gcc_64/include/QtCore/quuid.h \
		../6.6.3/gcc_64/include/QtCore/qendian.h \
		../6.6.3/gcc_64/include/QtCore/QDebug \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothAddress \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		../6.6.3/gcc_64/include/QtCore/QByteArray \
		../6.6.3/gcc_64/include/QtCore/QString \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothSocket \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetooth.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		../6.6.3/gcc_64/include/QtCore/QSharedPointer \
		../6.6.3/gcc_64/include/QtCore/QVariant \
		../6.6.3/gcc_64/include/QtCore/QTime \
		../6.6.3/gcc_64/include/QtCore/qdatetime.h \
		../6.6.3/gcc_64/include/QtCore/qcalendar.h \
		../6.6.3/gcc_64/include/QtCore/qlocale.h \
		utils/timing/Timer.h \
		utils/timing/TimeUtils.h \
		mb_master/sm_mb_master_impl.h \
		nanoModbus/nanomodbus.h \
		mb_master/sm_modbus_define.h \
		moc_predefs.h \
		../6.6.3/gcc_64/libexec/moc
	/home/lekhacvuong/Qt/6.6.3/gcc_64/libexec/moc $(DEFINES) --include /home/lekhacvuong/Qt/untitled/moc_predefs.h -I/home/lekhacvuong/Qt/6.6.3/gcc_64/mkspecs/linux-g++ -I/home/lekhacvuong/Qt/untitled -I/home/lekhacvuong/Qt/untitled/nanoModbus -I/home/lekhacvuong/Qt/untitled/mb_master -I/home/lekhacvuong/Qt/untitled/utils -I/home/lekhacvuong/Qt/untitled/utils/timing -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtWidgets -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtGui -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtBluetooth -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtNetwork -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtDBus -I/home/lekhacvuong/Qt/6.6.3/gcc_64/include/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../6.6.3/gcc_64/libexec/uic
	/home/lekhacvuong/Qt/6.6.3/gcc_64/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/QMainWindow \
		../6.6.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../6.6.3/gcc_64/include/QtGui/qtguiglobal.h \
		../6.6.3/gcc_64/include/QtCore/qglobal.h \
		../6.6.3/gcc_64/include/QtCore/qtversionchecks.h \
		../6.6.3/gcc_64/include/QtCore/qtconfiginclude.h \
		../6.6.3/gcc_64/include/QtCore/qconfig.h \
		../6.6.3/gcc_64/include/QtCore/qtcore-config.h \
		../6.6.3/gcc_64/include/QtCore/qtconfigmacros.h \
		../6.6.3/gcc_64/include/QtCore/qtcoreexports.h \
		../6.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../6.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../6.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../6.6.3/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../6.6.3/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../6.6.3/gcc_64/include/QtCore/qassert.h \
		../6.6.3/gcc_64/include/QtCore/qtnoop.h \
		../6.6.3/gcc_64/include/QtCore/qtypes.h \
		../6.6.3/gcc_64/include/QtCore/qtversion.h \
		../6.6.3/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../6.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../6.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../6.6.3/gcc_64/include/QtCore/qlogging.h \
		../6.6.3/gcc_64/include/QtCore/qflags.h \
		../6.6.3/gcc_64/include/QtCore/qcompare_impl.h \
		../6.6.3/gcc_64/include/QtCore/qatomic.h \
		../6.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../6.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../6.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../6.6.3/gcc_64/include/QtCore/qconstructormacros.h \
		../6.6.3/gcc_64/include/QtCore/qdarwinhelpers.h \
		../6.6.3/gcc_64/include/QtCore/qexceptionhandling.h \
		../6.6.3/gcc_64/include/QtCore/qforeach.h \
		../6.6.3/gcc_64/include/QtCore/qttypetraits.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionpointer.h \
		../6.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../6.6.3/gcc_64/include/QtCore/qmalloc.h \
		../6.6.3/gcc_64/include/QtCore/qminmax.h \
		../6.6.3/gcc_64/include/QtCore/qnumeric.h \
		../6.6.3/gcc_64/include/QtCore/qoverload.h \
		../6.6.3/gcc_64/include/QtCore/qswap.h \
		../6.6.3/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../6.6.3/gcc_64/include/QtCore/qtresource.h \
		../6.6.3/gcc_64/include/QtCore/qttranslation.h \
		../6.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../6.6.3/gcc_64/include/QtGui/qtgui-config.h \
		../6.6.3/gcc_64/include/QtGui/qtguiexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../6.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../6.6.3/gcc_64/include/QtCore/qnamespace.h \
		../6.6.3/gcc_64/include/QtCore/qtmetamacros.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qobject.h \
		../6.6.3/gcc_64/include/QtCore/qstring.h \
		../6.6.3/gcc_64/include/QtCore/qchar.h \
		../6.6.3/gcc_64/include/QtCore/qstringview.h \
		../6.6.3/gcc_64/include/QtCore/qbytearray.h \
		../6.6.3/gcc_64/include/QtCore/qrefcount.h \
		../6.6.3/gcc_64/include/QtCore/qarraydata.h \
		../6.6.3/gcc_64/include/QtCore/qpair.h \
		../6.6.3/gcc_64/include/QtCore/qarraydatapointer.h \
		../6.6.3/gcc_64/include/QtCore/qarraydataops.h \
		../6.6.3/gcc_64/include/QtCore/qcontainertools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qxptype_traits.h \
		../6.6.3/gcc_64/include/QtCore/q20functional.h \
		../6.6.3/gcc_64/include/QtCore/q20memory.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayview.h \
		../6.6.3/gcc_64/include/QtCore/qstringfwd.h \
		../6.6.3/gcc_64/include/QtCore/q20type_traits.h \
		../6.6.3/gcc_64/include/QtCore/qstringliteral.h \
		../6.6.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qlatin1stringview.h \
		../6.6.3/gcc_64/include/QtCore/qanystringview.h \
		../6.6.3/gcc_64/include/QtCore/qutf8stringview.h \
		../6.6.3/gcc_64/include/QtCore/qstringtokenizer.h \
		../6.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../6.6.3/gcc_64/include/QtCore/qlist.h \
		../6.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../6.6.3/gcc_64/include/QtCore/qiterator.h \
		../6.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../6.6.3/gcc_64/include/QtCore/qstringlist.h \
		../6.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../6.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../6.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qmetatype.h \
		../6.6.3/gcc_64/include/QtCore/qcompare.h \
		../6.6.3/gcc_64/include/QtCore/qdatastream.h \
		../6.6.3/gcc_64/include/QtCore/qiodevicebase.h \
		../6.6.3/gcc_64/include/QtCore/qfloat16.h \
		../6.6.3/gcc_64/include/QtCore/qmath.h \
		../6.6.3/gcc_64/include/QtCore/qiterable.h \
		../6.6.3/gcc_64/include/QtCore/qmetacontainer.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerinfo.h \
		../6.6.3/gcc_64/include/QtCore/qtaggedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qscopeguard.h \
		../6.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../6.6.3/gcc_64/include/QtCore/qbindingstorage.h \
		../6.6.3/gcc_64/include/QtCore/qmargins.h \
		../6.6.3/gcc_64/include/QtCore/q23utility.h \
		../6.6.3/gcc_64/include/QtGui/qaction.h \
		../6.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../6.6.3/gcc_64/include/QtGui/qicon.h \
		../6.6.3/gcc_64/include/QtCore/qsize.h \
		../6.6.3/gcc_64/include/QtGui/qpixmap.h \
		../6.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../6.6.3/gcc_64/include/QtCore/qrect.h \
		../6.6.3/gcc_64/include/QtCore/qpoint.h \
		../6.6.3/gcc_64/include/QtGui/qcolor.h \
		../6.6.3/gcc_64/include/QtGui/qrgb.h \
		../6.6.3/gcc_64/include/QtGui/qrgba64.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata.h \
		../6.6.3/gcc_64/include/QtGui/qimage.h \
		../6.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../6.6.3/gcc_64/include/QtGui/qtransform.h \
		../6.6.3/gcc_64/include/QtGui/qpolygon.h \
		../6.6.3/gcc_64/include/QtGui/qregion.h \
		../6.6.3/gcc_64/include/QtCore/qline.h \
		../6.6.3/gcc_64/include/QtCore/qvariant.h \
		../6.6.3/gcc_64/include/QtCore/qdebug.h \
		../6.6.3/gcc_64/include/QtCore/qtextstream.h \
		../6.6.3/gcc_64/include/QtCore/qstringconverter_base.h \
		../6.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../6.6.3/gcc_64/include/QtCore/qmap.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata_impl.h \
		../6.6.3/gcc_64/include/QtCore/qset.h \
		../6.6.3/gcc_64/include/QtCore/qhash.h \
		../6.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../6.6.3/gcc_64/include/QtGui/qpalette.h \
		../6.6.3/gcc_64/include/QtGui/qbrush.h \
		../6.6.3/gcc_64/include/QtGui/qfont.h \
		../6.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../6.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../6.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../6.6.3/gcc_64/include/QtGui/qcursor.h \
		../6.6.3/gcc_64/include/QtGui/qbitmap.h \
		../6.6.3/gcc_64/include/QtGui/qevent.h \
		../6.6.3/gcc_64/include/QtCore/qiodevice.h \
		../6.6.3/gcc_64/include/QtCore/qpointer.h \
		../6.6.3/gcc_64/include/QtCore/qurl.h \
		../6.6.3/gcc_64/include/QtGui/qeventpoint.h \
		../6.6.3/gcc_64/include/QtGui/qvector2d.h \
		../6.6.3/gcc_64/include/QtGui/qvectornd.h \
		../6.6.3/gcc_64/include/QtGui/qpointingdevice.h \
		../6.6.3/gcc_64/include/QtGui/qinputdevice.h \
		../6.6.3/gcc_64/include/QtGui/qscreen.h \
		../6.6.3/gcc_64/include/QtCore/QList \
		../6.6.3/gcc_64/include/QtCore/QObject \
		../6.6.3/gcc_64/include/QtCore/QRect \
		../6.6.3/gcc_64/include/QtCore/QSize \
		../6.6.3/gcc_64/include/QtCore/QSizeF \
		../6.6.3/gcc_64/include/QtGui/QTransform \
		../6.6.3/gcc_64/include/QtCore/qnativeinterface.h \
		../6.6.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothexports.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceInfo \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothUuid \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		../6.6.3/gcc_64/include/QtCore/QtGlobal \
		../6.6.3/gcc_64/include/QtCore/QMetaType \
		../6.6.3/gcc_64/include/QtCore/QUuid \
		../6.6.3/gcc_64/include/QtCore/quuid.h \
		../6.6.3/gcc_64/include/QtCore/qendian.h \
		../6.6.3/gcc_64/include/QtCore/QDebug \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothAddress \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		../6.6.3/gcc_64/include/QtCore/QByteArray \
		../6.6.3/gcc_64/include/QtCore/QString \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothSocket \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetooth.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		../6.6.3/gcc_64/include/QtCore/QSharedPointer \
		../6.6.3/gcc_64/include/QtCore/QVariant \
		../6.6.3/gcc_64/include/QtCore/QTime \
		../6.6.3/gcc_64/include/QtCore/qdatetime.h \
		../6.6.3/gcc_64/include/QtCore/qcalendar.h \
		../6.6.3/gcc_64/include/QtCore/qlocale.h \
		utils/timing/Timer.h \
		utils/timing/TimeUtils.h \
		mb_master/sm_mb_master_impl.h \
		nanoModbus/nanomodbus.h \
		mb_master/sm_modbus_define.h \
		../6.6.3/gcc_64/include/QtWidgets/QApplication \
		../6.6.3/gcc_64/include/QtWidgets/qapplication.h \
		../6.6.3/gcc_64/include/QtCore/qcoreapplication.h \
		../6.6.3/gcc_64/include/QtCore/qeventloop.h \
		../6.6.3/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../6.6.3/gcc_64/include/QtCore/qfuture.h \
		../6.6.3/gcc_64/include/QtCore/qfutureinterface.h \
		../6.6.3/gcc_64/include/QtCore/qmutex.h \
		../6.6.3/gcc_64/include/QtCore/qdeadlinetimer.h \
		../6.6.3/gcc_64/include/QtCore/qelapsedtimer.h \
		../6.6.3/gcc_64/include/QtCore/qtsan_impl.h \
		../6.6.3/gcc_64/include/QtCore/qresultstore.h \
		../6.6.3/gcc_64/include/QtCore/qfuture_impl.h \
		../6.6.3/gcc_64/include/QtCore/qthreadpool.h \
		../6.6.3/gcc_64/include/QtCore/qthread.h \
		../6.6.3/gcc_64/include/QtCore/qrunnable.h \
		../6.6.3/gcc_64/include/QtCore/qexception.h \
		../6.6.3/gcc_64/include/QtCore/qpromise.h \
		../6.6.3/gcc_64/include/QtGui/qguiapplication.h \
		../6.6.3/gcc_64/include/QtGui/qinputmethod.h \
		../6.6.3/gcc_64/include/QtGui/qguiapplication_platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/QMainWindow \
		../6.6.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../6.6.3/gcc_64/include/QtGui/qtguiglobal.h \
		../6.6.3/gcc_64/include/QtCore/qglobal.h \
		../6.6.3/gcc_64/include/QtCore/qtversionchecks.h \
		../6.6.3/gcc_64/include/QtCore/qtconfiginclude.h \
		../6.6.3/gcc_64/include/QtCore/qconfig.h \
		../6.6.3/gcc_64/include/QtCore/qtcore-config.h \
		../6.6.3/gcc_64/include/QtCore/qtconfigmacros.h \
		../6.6.3/gcc_64/include/QtCore/qtcoreexports.h \
		../6.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../6.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../6.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../6.6.3/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../6.6.3/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../6.6.3/gcc_64/include/QtCore/qassert.h \
		../6.6.3/gcc_64/include/QtCore/qtnoop.h \
		../6.6.3/gcc_64/include/QtCore/qtypes.h \
		../6.6.3/gcc_64/include/QtCore/qtversion.h \
		../6.6.3/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../6.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../6.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../6.6.3/gcc_64/include/QtCore/qlogging.h \
		../6.6.3/gcc_64/include/QtCore/qflags.h \
		../6.6.3/gcc_64/include/QtCore/qcompare_impl.h \
		../6.6.3/gcc_64/include/QtCore/qatomic.h \
		../6.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../6.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../6.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../6.6.3/gcc_64/include/QtCore/qconstructormacros.h \
		../6.6.3/gcc_64/include/QtCore/qdarwinhelpers.h \
		../6.6.3/gcc_64/include/QtCore/qexceptionhandling.h \
		../6.6.3/gcc_64/include/QtCore/qforeach.h \
		../6.6.3/gcc_64/include/QtCore/qttypetraits.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionpointer.h \
		../6.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../6.6.3/gcc_64/include/QtCore/qmalloc.h \
		../6.6.3/gcc_64/include/QtCore/qminmax.h \
		../6.6.3/gcc_64/include/QtCore/qnumeric.h \
		../6.6.3/gcc_64/include/QtCore/qoverload.h \
		../6.6.3/gcc_64/include/QtCore/qswap.h \
		../6.6.3/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../6.6.3/gcc_64/include/QtCore/qtresource.h \
		../6.6.3/gcc_64/include/QtCore/qttranslation.h \
		../6.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../6.6.3/gcc_64/include/QtGui/qtgui-config.h \
		../6.6.3/gcc_64/include/QtGui/qtguiexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../6.6.3/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../6.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../6.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../6.6.3/gcc_64/include/QtCore/qnamespace.h \
		../6.6.3/gcc_64/include/QtCore/qtmetamacros.h \
		../6.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../6.6.3/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qobject.h \
		../6.6.3/gcc_64/include/QtCore/qstring.h \
		../6.6.3/gcc_64/include/QtCore/qchar.h \
		../6.6.3/gcc_64/include/QtCore/qstringview.h \
		../6.6.3/gcc_64/include/QtCore/qbytearray.h \
		../6.6.3/gcc_64/include/QtCore/qrefcount.h \
		../6.6.3/gcc_64/include/QtCore/qarraydata.h \
		../6.6.3/gcc_64/include/QtCore/qpair.h \
		../6.6.3/gcc_64/include/QtCore/qarraydatapointer.h \
		../6.6.3/gcc_64/include/QtCore/qarraydataops.h \
		../6.6.3/gcc_64/include/QtCore/qcontainertools_impl.h \
		../6.6.3/gcc_64/include/QtCore/qxptype_traits.h \
		../6.6.3/gcc_64/include/QtCore/q20functional.h \
		../6.6.3/gcc_64/include/QtCore/q20memory.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qbytearrayview.h \
		../6.6.3/gcc_64/include/QtCore/qstringfwd.h \
		../6.6.3/gcc_64/include/QtCore/q20type_traits.h \
		../6.6.3/gcc_64/include/QtCore/qstringliteral.h \
		../6.6.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qlatin1stringview.h \
		../6.6.3/gcc_64/include/QtCore/qanystringview.h \
		../6.6.3/gcc_64/include/QtCore/qutf8stringview.h \
		../6.6.3/gcc_64/include/QtCore/qstringtokenizer.h \
		../6.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../6.6.3/gcc_64/include/QtCore/qlist.h \
		../6.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../6.6.3/gcc_64/include/QtCore/qiterator.h \
		../6.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../6.6.3/gcc_64/include/QtCore/qstringlist.h \
		../6.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../6.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../6.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../6.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qmetatype.h \
		../6.6.3/gcc_64/include/QtCore/qcompare.h \
		../6.6.3/gcc_64/include/QtCore/qdatastream.h \
		../6.6.3/gcc_64/include/QtCore/qiodevicebase.h \
		../6.6.3/gcc_64/include/QtCore/qfloat16.h \
		../6.6.3/gcc_64/include/QtCore/qmath.h \
		../6.6.3/gcc_64/include/QtCore/qiterable.h \
		../6.6.3/gcc_64/include/QtCore/qmetacontainer.h \
		../6.6.3/gcc_64/include/QtCore/qcontainerinfo.h \
		../6.6.3/gcc_64/include/QtCore/qtaggedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qscopeguard.h \
		../6.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../6.6.3/gcc_64/include/QtCore/qbindingstorage.h \
		../6.6.3/gcc_64/include/QtCore/qmargins.h \
		../6.6.3/gcc_64/include/QtCore/q23utility.h \
		../6.6.3/gcc_64/include/QtGui/qaction.h \
		../6.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../6.6.3/gcc_64/include/QtGui/qicon.h \
		../6.6.3/gcc_64/include/QtCore/qsize.h \
		../6.6.3/gcc_64/include/QtGui/qpixmap.h \
		../6.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../6.6.3/gcc_64/include/QtCore/qrect.h \
		../6.6.3/gcc_64/include/QtCore/qpoint.h \
		../6.6.3/gcc_64/include/QtGui/qcolor.h \
		../6.6.3/gcc_64/include/QtGui/qrgb.h \
		../6.6.3/gcc_64/include/QtGui/qrgba64.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata.h \
		../6.6.3/gcc_64/include/QtGui/qimage.h \
		../6.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../6.6.3/gcc_64/include/QtGui/qtransform.h \
		../6.6.3/gcc_64/include/QtGui/qpolygon.h \
		../6.6.3/gcc_64/include/QtGui/qregion.h \
		../6.6.3/gcc_64/include/QtCore/qline.h \
		../6.6.3/gcc_64/include/QtCore/qvariant.h \
		../6.6.3/gcc_64/include/QtCore/qdebug.h \
		../6.6.3/gcc_64/include/QtCore/qtextstream.h \
		../6.6.3/gcc_64/include/QtCore/qstringconverter_base.h \
		../6.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../6.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../6.6.3/gcc_64/include/QtCore/qmap.h \
		../6.6.3/gcc_64/include/QtCore/qshareddata_impl.h \
		../6.6.3/gcc_64/include/QtCore/qset.h \
		../6.6.3/gcc_64/include/QtCore/qhash.h \
		../6.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../6.6.3/gcc_64/include/QtGui/qpalette.h \
		../6.6.3/gcc_64/include/QtGui/qbrush.h \
		../6.6.3/gcc_64/include/QtGui/qfont.h \
		../6.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../6.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../6.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../6.6.3/gcc_64/include/QtGui/qcursor.h \
		../6.6.3/gcc_64/include/QtGui/qbitmap.h \
		../6.6.3/gcc_64/include/QtGui/qevent.h \
		../6.6.3/gcc_64/include/QtCore/qiodevice.h \
		../6.6.3/gcc_64/include/QtCore/qpointer.h \
		../6.6.3/gcc_64/include/QtCore/qurl.h \
		../6.6.3/gcc_64/include/QtGui/qeventpoint.h \
		../6.6.3/gcc_64/include/QtGui/qvector2d.h \
		../6.6.3/gcc_64/include/QtGui/qvectornd.h \
		../6.6.3/gcc_64/include/QtGui/qpointingdevice.h \
		../6.6.3/gcc_64/include/QtGui/qinputdevice.h \
		../6.6.3/gcc_64/include/QtGui/qscreen.h \
		../6.6.3/gcc_64/include/QtCore/QList \
		../6.6.3/gcc_64/include/QtCore/QObject \
		../6.6.3/gcc_64/include/QtCore/QRect \
		../6.6.3/gcc_64/include/QtCore/QSize \
		../6.6.3/gcc_64/include/QtCore/QSizeF \
		../6.6.3/gcc_64/include/QtGui/QTransform \
		../6.6.3/gcc_64/include/QtCore/qnativeinterface.h \
		../6.6.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		../6.6.3/gcc_64/include/QtBluetooth/qtbluetoothexports.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothDeviceInfo \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothUuid \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		../6.6.3/gcc_64/include/QtCore/QtGlobal \
		../6.6.3/gcc_64/include/QtCore/QMetaType \
		../6.6.3/gcc_64/include/QtCore/QUuid \
		../6.6.3/gcc_64/include/QtCore/quuid.h \
		../6.6.3/gcc_64/include/QtCore/qendian.h \
		../6.6.3/gcc_64/include/QtCore/QDebug \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothAddress \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		../6.6.3/gcc_64/include/QtCore/QByteArray \
		../6.6.3/gcc_64/include/QtCore/QString \
		../6.6.3/gcc_64/include/QtBluetooth/QBluetoothSocket \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetooth.h \
		../6.6.3/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		../6.6.3/gcc_64/include/QtCore/QSharedPointer \
		../6.6.3/gcc_64/include/QtCore/QVariant \
		../6.6.3/gcc_64/include/QtCore/QTime \
		../6.6.3/gcc_64/include/QtCore/qdatetime.h \
		../6.6.3/gcc_64/include/QtCore/qcalendar.h \
		../6.6.3/gcc_64/include/QtCore/qlocale.h \
		utils/timing/Timer.h \
		utils/timing/TimeUtils.h \
		mb_master/sm_mb_master_impl.h \
		nanoModbus/nanomodbus.h \
		mb_master/sm_modbus_define.h \
		ui_mainwindow.h \
		../6.6.3/gcc_64/include/QtWidgets/QApplication \
		../6.6.3/gcc_64/include/QtWidgets/qapplication.h \
		../6.6.3/gcc_64/include/QtCore/qcoreapplication.h \
		../6.6.3/gcc_64/include/QtCore/qeventloop.h \
		../6.6.3/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../6.6.3/gcc_64/include/QtCore/qfuture.h \
		../6.6.3/gcc_64/include/QtCore/qfutureinterface.h \
		../6.6.3/gcc_64/include/QtCore/qmutex.h \
		../6.6.3/gcc_64/include/QtCore/qdeadlinetimer.h \
		../6.6.3/gcc_64/include/QtCore/qelapsedtimer.h \
		../6.6.3/gcc_64/include/QtCore/qtsan_impl.h \
		../6.6.3/gcc_64/include/QtCore/qresultstore.h \
		../6.6.3/gcc_64/include/QtCore/qfuture_impl.h \
		../6.6.3/gcc_64/include/QtCore/qthreadpool.h \
		../6.6.3/gcc_64/include/QtCore/qthread.h \
		../6.6.3/gcc_64/include/QtCore/qrunnable.h \
		../6.6.3/gcc_64/include/QtCore/qexception.h \
		../6.6.3/gcc_64/include/QtCore/qpromise.h \
		../6.6.3/gcc_64/include/QtGui/qguiapplication.h \
		../6.6.3/gcc_64/include/QtGui/qinputmethod.h \
		../6.6.3/gcc_64/include/QtGui/qguiapplication_platform.h \
		../6.6.3/gcc_64/include/QtWidgets/QCheckBox \
		../6.6.3/gcc_64/include/QtWidgets/qcheckbox.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../6.6.3/gcc_64/include/QtWidgets/QComboBox \
		../6.6.3/gcc_64/include/QtWidgets/qcombobox.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../6.6.3/gcc_64/include/QtWidgets/qstyleoption.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../6.6.3/gcc_64/include/QtGui/qvalidator.h \
		../6.6.3/gcc_64/include/QtCore/qregularexpression.h \
		../6.6.3/gcc_64/include/QtWidgets/qslider.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractslider.h \
		../6.6.3/gcc_64/include/QtWidgets/qstyle.h \
		../6.6.3/gcc_64/include/QtWidgets/qtabbar.h \
		../6.6.3/gcc_64/include/QtWidgets/qrubberband.h \
		../6.6.3/gcc_64/include/QtWidgets/qframe.h \
		../6.6.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		../6.6.3/gcc_64/include/QtWidgets/QHBoxLayout \
		../6.6.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../6.6.3/gcc_64/include/QtWidgets/qlayout.h \
		../6.6.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../6.6.3/gcc_64/include/QtWidgets/qgridlayout.h \
		../6.6.3/gcc_64/include/QtWidgets/QLabel \
		../6.6.3/gcc_64/include/QtWidgets/qlabel.h \
		../6.6.3/gcc_64/include/QtGui/qpicture.h \
		../6.6.3/gcc_64/include/QtGui/qtextdocument.h \
		../6.6.3/gcc_64/include/QtWidgets/QLineEdit \
		../6.6.3/gcc_64/include/QtWidgets/qlineedit.h \
		../6.6.3/gcc_64/include/QtGui/qtextcursor.h \
		../6.6.3/gcc_64/include/QtGui/qtextformat.h \
		../6.6.3/gcc_64/include/QtGui/qpen.h \
		../6.6.3/gcc_64/include/QtGui/qtextoption.h \
		../6.6.3/gcc_64/include/QtWidgets/QListWidget \
		../6.6.3/gcc_64/include/QtWidgets/qlistwidget.h \
		../6.6.3/gcc_64/include/QtWidgets/qlistview.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		../6.6.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../6.6.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		../6.6.3/gcc_64/include/QtWidgets/QMenuBar \
		../6.6.3/gcc_64/include/QtWidgets/qmenubar.h \
		../6.6.3/gcc_64/include/QtWidgets/qmenu.h \
		../6.6.3/gcc_64/include/QtWidgets/QPushButton \
		../6.6.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../6.6.3/gcc_64/include/QtWidgets/QSlider \
		../6.6.3/gcc_64/include/QtWidgets/QStatusBar \
		../6.6.3/gcc_64/include/QtWidgets/qstatusbar.h \
		../6.6.3/gcc_64/include/QtWidgets/QTabWidget \
		../6.6.3/gcc_64/include/QtWidgets/QTimeEdit \
		../6.6.3/gcc_64/include/QtWidgets/qdatetimeedit.h \
		../6.6.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../6.6.3/gcc_64/include/QtWidgets/QWidget \
		utils/sm_logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sm_mb_master_impl.o: mb_master/sm_mb_master_impl.c mb_master/sm_mb_master_impl.h \
		nanoModbus/nanomodbus.h \
		mb_master/sm_modbus_define.h \
		utils/sm_logger.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sm_mb_master_impl.o mb_master/sm_mb_master_impl.c

nanomodbus.o: nanoModbus/nanomodbus.c nanoModbus/nanomodbus.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o nanomodbus.o nanoModbus/nanomodbus.c

sm_logger.o: utils/sm_logger.c utils/sm_logger.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sm_logger.o utils/sm_logger.c

DateTime.o: utils/timing/DateTime.cpp utils/timing/DateTime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DateTime.o utils/timing/DateTime.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/untitled/bin || mkdir -p $(INSTALL_ROOT)/opt/untitled/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/untitled/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/untitled/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/untitled/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

